module.exports = {
    SUCC_OPERATION: 0,
    SUCC_CREATED : 10,
    BAD_REQUEST : 24,
    NOT_ACTIVE_USER : 103,
    ACCESS_FORBIDDEN : 104,
    CONFLICT_REQUEST : 201,
    NO_SUCH_RESOURCE : 202,
    SERVER_ERROR: 203,
    TAG_ALRAEDY_EXISTS : 204,
    USER_ALREADY_EXISTS : 205,
    BAD_REQUEST: 400
};